import { test, expect } from '@playwright/test';
test('real browser: publish, run, task, approval, timer, resolve, export and RU/EN', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Когда сервис падает, план уже есть.' })).toBeVisible();
  await page.screenshot({ path: 'screenshots/01-welcome-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Начать в личном пространстве' }).click();
  await page.getByRole('button', { name: 'Перейти к сценариям' }).click();
  await page.getByRole('button', { name: 'Создать первый сценарий' }).click();
  await page.getByRole('button', { name: 'Взять за основу: восстановление' }).click();
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByText('Черновик сохранён', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Опубликовать', exact: true }).click();
  await expect(page.getByText('Сценарий опубликован. Теперь можно запустить инцидент.')).toBeVisible();
  await page.screenshot({ path: 'screenshots/02-playbook-editor.png', fullPage: true });
  await page.getByRole('link', { name: /Инциденты/ }).click();
  await page.getByRole('button', { name: 'Запустить первый инцидент' }).click();
  await page.getByLabel('Название инцидента').fill('Ошибка платёжного API');
  await page.getByLabel('Сервис', { exact: true }).fill('payments-api');
  await page.getByRole('button', { name: 'Создать и запустить' }).click();
  await expect(page.getByRole('heading', { name: 'Выполните задачу' })).toBeVisible();
  await page.screenshot({ path: 'screenshots/03-incident-action.png', fullPage: true });
  await page.getByLabel('Результат или обоснование').fill('Проверены метрики. Причина: недоступен пул соединений.');
  await page.getByRole('button', { name: 'Подтвердить выполнение' }).click();
  await expect(page.getByRole('heading', { name: 'Нужно ваше решение' })).toBeVisible();
  await page.getByLabel('Результат или обоснование').fill('Восстановление согласовано после проверки метрик.');
  await page.getByRole('button', { name: 'Согласовать и продолжить' }).click();
  await expect(page.getByRole('heading', { name: 'Сценарий выполнен' })).toBeVisible({ timeout: 15000 });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Сценарий выполнен' })).toBeVisible();
  await page.screenshot({ path: 'screenshots/04-run-completed.png', fullPage: true });
  const response = await page.request.get(await page.getByRole('link', { name: 'Экспорт' }).getAttribute('href'));
  const exported = await response.json(); expect(exported.status).toBe('completed'); expect(exported.incidentStatus).toBe('resolved'); expect(exported.events.some(e => e.type === 'action.approve')).toBeTruthy();
  await page.getByRole('button', { name: 'Switch to English' }).click();
  await expect(page.getByRole('heading', { name: 'Playbook completed' })).toBeVisible();
  await page.getByRole('link', { name: /Analytics/ }).click();
  await expect(page.getByRole('heading', { name: 'Response analytics' })).toBeVisible();
  await page.screenshot({ path: 'screenshots/05-analytics-en.png', fullPage: true });
  expect(errors).toEqual([]);
});
test('phone: first run, accessible navigation and no horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Когда сервис падает, план уже есть.' })).toBeVisible();
  await page.screenshot({ path: 'screenshots/06-welcome-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Начать в личном пространстве' }).click();
  await expect(page.getByRole('heading', { name: 'Каждому инциденту — следующий шаг' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: 'screenshots/07-workspace-mobile.png', fullPage: true });
  await page.getByRole('link', { name: /Сценарии/ }).click();
  await page.getByRole('button', { name: 'Создать первый сценарий' }).click();
  await page.getByLabel('Название сценария').fill('Мобильный сценарий');
  await page.getByLabel('Действие или сообщение').fill('Проверить метрики');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByText('Черновик сохранён', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});
